name = "team-schedule-api"
main = "worker-schedule-agents.ts"
compatibility_date = "2025-08-28"

# When deploying via Cloudflare “Workers Builds” (Git integration with
# `npx wrangler versions upload`), configure the KV binding in the Cloudflare
# dashboard (Worker > Settings > Bindings) and DO NOT hard-code an `id` here.
# This avoids build-time failures when placeholder IDs are present.
#
# For local dev with `wrangler dev`, you can optionally uncomment and provide
# a preview-only binding or your real KV id:
#

## Note: For Workers Builds via Versions, bindings are managed in the dashboard.
## Do not declare kv_namespaces here unless you also provide an id; Wrangler v3 requires it.

[vars]
# These can be overridden in Cloudflare dashboard (Settings > Variables).
# ADMIN_PASSWORD = ""
# SITE_PASSWORD = ""
# ALLOWED_ORIGINS = "https://teamschedule.cc,https://schedule.your-dev-domain"
# COOKIE_DOMAIN = ".teamschedule.cc"
# COOKIE_SECURE = "true"
# COOKIE_SAMESITE = "Lax"
# REQUIRE_SITE_SESSION = "true"
# DATA_KEY = "schedule.json"
# Prefer KV by default; we’ll flip this during cutover
USE_D1 = "0"

[[d1_databases]]
binding = "DB"
database_name = "schedule2"
database_id = "50d218ac-7a3f-4397-b60a-dab4b131838c"
