name = "team-schedule-api"
main = "worker-schedule-agents.ts"
compatibility_date = "2025-08-28"

# Wrangler-first deploys: wrangler.toml is the source of truth for bindings.
# We bind KV here (with a concrete id) and deploy via `wrangler deploy`.

# D1 database bindings (add your database_id values after creating D1)
# NOTE: These are placeholders. Uncomment and set the correct database_id(s) when ready.
# [[d1_databases]]
# binding = "DB"
# database_name = "team-schedule-prod"
# database_id = "<YOUR-PROD-DATABASE-ID>"

[vars]
# Secrets like ADMIN_PASSWORD and SITE_PASSWORD should be set via:
#   wrangler secret put ADMIN_PASSWORD
#   wrangler secret put SITE_PASSWORD
# Non-secret vars can live here and be overridden per-environment if needed.
# When using the custom domain (api.teamschedule.cc + teamschedule.cc), keep origins first-party
# to reduce SSO/VPN filtering false positives and allow credentialed requests.
# First-party only
ALLOWED_ORIGINS = "https://teamschedule.cc,https://www.teamschedule.cc"
# Scope cookies to the apex so api + www share sessions when needed.
COOKIE_DOMAIN = ".teamschedule.cc"
COOKIE_SECURE = "true"
COOKIE_SAMESITE = "Lax"
REQUIRE_SITE_SESSION = "false"
# Optional: override the KV key name for the schedule document
# DATA_KEY = "schedule.json"

# Freeze storage to KV (D1 optional endpoints will 503 without a DB binding)
USE_D1 = "0"

# KV namespace binding (prod). For previews/local, you may also set preview_id.
[[kv_namespaces]]
binding = "SCHEDULE_KV"
id = "b3cf4bb860cb4e49a79f70f6b79e4606"
# preview_id = "<your-preview-namespace-id>"

# If you later want separate environments, add [env.staging] / [env.prod]
# blocks with their own kv_namespaces arrays and vars.

# -----------------
# Staging environment
[env.staging]
name = "team-schedule-api-staging"

[env.staging.vars]
ALLOWED_ORIGINS = "https://staging.teamschedule.cc,https://next.teamschedule.cc,https://schedule2-staging.pages.dev,*.schedule2-staging.pages.dev,*.teamschedule.cc"
COOKIE_DOMAIN = ""
COOKIE_SECURE = "true"
COOKIE_SAMESITE = "None"
REQUIRE_SITE_SESSION = "true"
USE_D1 = "0"

[[env.staging.kv_namespaces]]
binding = "SCHEDULE_KV"
id = "83ab5fcb1c2e4a3b8ae75ea5240f31eb"

# Staging D1 binding (uncomment and fill once created)
# [[env.staging.d1_databases]]
# binding = "DB"
# database_name = "team-schedule-staging"
# database_id = "<YOUR-STAGING-DATABASE-ID>"
