name = "team-schedule-api"
main = "worker-schedule-agents.ts"
compatibility_date = "2025-08-28"

# If you want to test via `npm run dev`, Wrangler will use these bindings locally.
# Put secrets in `.dev.vars` (not committed) or set via `wrangler secret put`.

[[kv_namespaces]]
binding = "SCHEDULE_KV"
# Production KV namespace for sessions (and legacy doc fallback)
# Namespace title example: "SESSIONS"
id = "a99ca3fba4c04b32bb9f138a64b2c95a"

[vars]
# Non‑secret defaults for Production. Secrets (e.g., RESEND_API_KEY, ADMIN_PASSWORD,
# SITE_PASSWORD) must be set via `wrangler secret put` or the Dashboard.

# CORS allowlist for the web app (Pages origin + custom domain)
ALLOWED_ORIGINS = "https://teamschedule.cc,https://teamschedulecc.pages.dev"

# Cookies across app + API subdomains
COOKIE_DOMAIN = ".teamschedule.cc"
COOKIE_SECURE = "true"
COOKIE_SAMESITE = "None"

# Gate reads behind a site session
REQUIRE_SITE_SESSION = "false"

# Redirect base after magic verify
APP_REDIRECT_BASE = "https://teamschedule.cc"

# Magic link policy (non‑secret)
MAGIC_ALLOWED_DOMAINS = "betabionics.com"
MAGIC_FROM_EMAIL = "Team Schedule <auth@teamschedule.cc>"

# Prefer D1 by default; KV remains a fallback if USE_D1="0"
USE_D1 = "0"

[[d1_databases]]
binding = "DB"
database_name = "schedule2"
database_id = "50d218ac-7a3f-4397-b60a-dab4b131838c"

[env.preview]
  [[env.preview.kv_namespaces]]
  binding = "SCHEDULE_KV"
  id = "a99ca3fba4c04b32bb9f138a64b2c95a"

  [[env.preview.d1_databases]]
  binding = "DB"
  database_name = "schedule2"
  database_id = "50d218ac-7a3f-4397-b60a-dab4b131838c"

  [env.preview.vars]
  REQUIRE_SITE_SESSION = "false"
  ALLOWED_ORIGINS = "*"
  COOKIE_DOMAIN = ""
  COOKIE_SECURE = "true"
  COOKIE_SAMESITE = "None"
  APP_REDIRECT_BASE = "https://preview.schedule2-staging.pages.dev"
  MAGIC_ALLOWED_DOMAINS = "betabionics.com"
  MAGIC_FROM_EMAIL = "Team Schedule <auth@teamschedule.cc>"
  USE_D1 = "0"
