name = "team-schedule-api"
main = "worker-schedule-agents.ts"
compatibility_date = "2025-08-28"

# If you want to test via `npm run dev`, Wrangler will use these bindings locally.
# Put secrets in `.dev.vars` (not committed) or set via `wrangler secret put`.

[[kv_namespaces]]
binding = "SCHEDULE_KV"
# Production KV namespace for sessions (and legacy doc fallback)
# Namespace title example: "SESSIONS"
id = "a99ca3fba4c04b32bb9f138a64b2c95a"

[vars]
# These can be overridden in Cloudflare dashboard (Settings > Variables).
# ADMIN_PASSWORD = ""
# SITE_PASSWORD = ""
# ALLOWED_ORIGINS = "https://teamschedule.cc,https://schedule.your-dev-domain"
# COOKIE_DOMAIN = ".teamschedule.cc"
# COOKIE_SECURE = "true"
# COOKIE_SAMESITE = "Lax"
# REQUIRE_SITE_SESSION = "true"
# DATA_KEY = "schedule.json"
# Prefer D1 by default; KV remains a fallback if USE_D1="0"
USE_D1 = "1"

[[d1_databases]]
binding = "DB"
database_name = "schedule2"
database_id = "50d218ac-7a3f-4397-b60a-dab4b131838c"
