name = "team-schedule-api"
main = "worker-schedule-agents.ts"
compatibility_date = "2025-08-28"

# If you want to test via `npm run dev`, Wrangler will use these bindings locally.
# Put secrets in `.dev.vars` (not committed) or set via `wrangler secret put`.

[[kv_namespaces]]
binding = "SCHEDULE_KV"
# Production KV namespace for sessions (and legacy doc fallback)
# Namespace title example: "SESSIONS"
id = "a99ca3fba4c04b32bb9f138a64b2c95a"

[vars]
<<<<<<< HEAD
# These can be overridden in Cloudflare dashboard (Settings > Variables).
# ADMIN_PASSWORD = ""
# ALLOWED_ORIGINS = "https://teamschedule.cc,https://schedule.your-dev-domain"
# COOKIE_DOMAIN = ".teamschedule.cc"
# COOKIE_SECURE = "true"
# COOKIE_SAMESITE = "Lax"
# DATA_KEY = "schedule.json"
# Prefer KV by default; we’ll flip this during cutover
=======
# Non‑secret defaults for Production. Secrets (e.g., RESEND_API_KEY, ADMIN_PASSWORD,
# SITE_PASSWORD) must be set via `wrangler secret put` or the Dashboard.

# CORS allowlist for the web app (Pages origin + custom domain)
ALLOWED_ORIGINS = "https://teamschedule.cc,https://teamschedulecc.pages.dev"

# Cookies across app + API subdomains
COOKIE_DOMAIN = ".teamschedule.cc"
COOKIE_SECURE = "true"
COOKIE_SAMESITE = "None"

# Gate reads behind a site session
REQUIRE_SITE_SESSION = "false"

# Redirect base after magic verify
APP_REDIRECT_BASE = "https://teamschedule.cc"

# Magic link policy (non‑secret)
MAGIC_ALLOWED_DOMAINS = "betabionics.com"
MAGIC_FROM_EMAIL = "Team Schedule <auth@teamschedule.cc>"

# Prefer D1 by default; KV remains a fallback if USE_D1="0"
>>>>>>> c76a6b2a8c4404b7ec7131ea39ccd1b1d3b55a13
USE_D1 = "0"

[[d1_databases]]
binding = "DB"
database_name = "schedule2"
database_id = "50d218ac-7a3f-4397-b60a-dab4b131838c"
