name: Deploy Staging to Cloudflare Pages

on:
  push:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Prepare staging env
        run: |
          # If a repo-level override is provided, write it to .env.production
          if [ -n "${{ secrets.VITE_SCHEDULE_API_BASE_STAGING }}" ]; then
            echo "VITE_SCHEDULE_API_BASE=${{ secrets.VITE_SCHEDULE_API_BASE_STAGING }}" > .env.production
          elif [ -f .env.production.staging ]; then
            cp .env.production.staging .env.production
          else
            # Fallback to staging workers.dev API
            echo "VITE_SCHEDULE_API_BASE=https://staging-team-schedule-api.phorbie.workers.dev" > .env.production
          fi
          # Explicitly avoid forcing env base on staging unless we intentionally set VITE_FORCE_API_BASE=yes
          echo "VITE_FORCE_API_BASE=no" >> .env.production

      - name: Validate Cloudflare env
        run: |
          [ -n "${{ secrets.CF_API_TOKEN }}" ] || { echo "CF_API_TOKEN missing"; exit 1; }
          [ -n "${{ secrets.CF_ACCOUNT_ID }}" ] || { echo "CF_ACCOUNT_ID missing"; exit 1; }
          PRJ="${{ secrets.CF_PAGES_PROJECT_NAME }}"; if [ -z "$PRJ" ]; then PRJ="schedule2-staging"; fi
          echo "Using Pages project: $PRJ"
          echo "PRJ=$PRJ" >> $GITHUB_ENV

      - name: Build
        run: npm run build

      - name: Wrangler info (diagnostic)
        run: |
          npx --yes wrangler@3 --version
          npx --yes wrangler@3 whoami
          npx --yes wrangler@3 pages project list | grep -E "^${PRJ}\b" || true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      - name: Ensure Cloudflare Pages project exists (idempotent)
        run: |
          npx --yes wrangler@3 pages project create "${PRJ}" \
            --production-branch=staging --no-interactive || true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      - name: Ensure production branch is 'staging' (idempotent)
        run: |
          npx --yes wrangler@3 pages project update "${PRJ}" \
            --production-branch=staging --no-interactive || true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      - name: Ensure custom domain attached (idempotent)
        run: |
          DOMAIN="staging.teamschedule.cc"
          npx --yes wrangler@3 pages domain add "${PRJ}" "$DOMAIN" --no-interactive || true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      - name: "Publish to Cloudflare Pages (preview: branch=staging)"
        run: |
          npx --yes wrangler@3 pages deploy ./dist --project-name "${PRJ}" --branch staging --commit-dirty=true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      - name: Publish to Cloudflare Pages (production)
        run: |
          npx --yes wrangler@3 pages deploy ./dist --project-name "${PRJ}" --production --commit-dirty=true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      - name: List Pages domains (diagnostic)
        run: |
          npx --yes wrangler@3 pages domain list "${PRJ}"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      - name: List deployments (diagnostic)
        run: |
          echo "Production deployments:" && npx --yes wrangler@3 pages deployment list "${PRJ}" --production || true
          echo "Preview deployments:" && npx --yes wrangler@3 pages deployment list "${PRJ}" || true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
