name: Deploy API (staging) to Cloudflare Workers

on:
  push:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  deploy-staging-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolve Cloudflare env
        env:
          SECRET_CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          SECRET_CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          # Canonicalize Cloudflare env vars from available secrets (current repo uses CF_* secrets)
          CF_API_TOKEN_INPUT="${SECRET_CF_API_TOKEN}"
          CF_ACCOUNT_ID_INPUT="${SECRET_CF_ACCOUNT_ID}"

          echo "CLOUDFLARE_API_TOKEN=$CF_API_TOKEN_INPUT" >> "$GITHUB_ENV"
          echo "CLOUDFLARE_ACCOUNT_ID=$CF_ACCOUNT_ID_INPUT" >> "$GITHUB_ENV"
          # Legacy aliases for compatibility
          echo "CF_API_TOKEN=$CF_API_TOKEN_INPUT" >> "$GITHUB_ENV"
          echo "CF_ACCOUNT_ID=$CF_ACCOUNT_ID_INPUT" >> "$GITHUB_ENV"

      - name: List repo (diagnostic)
        run: |
          pwd
          ls -la

      - name: Validate Cloudflare credentials
        run: |
          missing=0
          [ -n "${CLOUDFLARE_API_TOKEN}" ] || { echo "CLOUDFLARE_API_TOKEN missing"; missing=1; }
          [ -n "${CLOUDFLARE_ACCOUNT_ID}" ] || { echo "CLOUDFLARE_ACCOUNT_ID missing"; missing=1; }
          # Compatibility checks (non-fatal)
          [ -n "${CF_API_TOKEN}" ] || echo "(compat) CF_API_TOKEN missing"
          [ -n "${CF_ACCOUNT_ID}" ] || echo "(compat) CF_ACCOUNT_ID missing"
          [ "$missing" -eq 0 ] || exit 1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Wrangler diagnostics
        run: |
          npx --yes wrangler@3 --version
          npx --yes wrangler@3 whoami

      - name: Verify account matches CLOUDFLARE_ACCOUNT_ID
        run: |
          set -e
          json=$(npx --yes wrangler@3 whoami --format=json || true)
          echo "$json" | jq . >/dev/null 2>&1 || { echo "wrangler whoami (json) unavailable"; exit 0; }
          acc=$(echo "$json" | jq -r '.account_id // .accountId // empty')
          if [ -n "$acc" ] && [ -n "$CLOUDFLARE_ACCOUNT_ID" ]; then
            if [ "$acc" != "$CLOUDFLARE_ACCOUNT_ID" ]; then
              echo "Account mismatch: whoami=$acc vs CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID"; exit 1;
            else
              echo "Account verified: $acc"
            fi
          fi

      - name: List KV namespaces (diagnostic)
        working-directory: team-schedule-api
        run: |
          echo "Listing KV namespaces for account..."
          npx --yes wrangler@3 kv namespace list || true

      - name: Dry-run build with Wrangler (no deploy)
        working-directory: team-schedule-api
        run: |
          ls -la
          cat wrangler.toml
          npx --yes wrangler@3 deploy --env staging --config wrangler.toml --account-id "$CLOUDFLARE_ACCOUNT_ID" --dry-run --outdir .wrangler_tmp

      - name: Deploy with Wrangler (staging)
        working-directory: team-schedule-api
        run: |
          npx --yes wrangler@3.90.0 deploy --env staging --config wrangler.toml --account-id "$CLOUDFLARE_ACCOUNT_ID" --verbose
