name: Deploy API (staging) to Cloudflare Workers

on:
  push:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  deploy-staging-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List repo (diagnostic)
        run: |
          pwd
          ls -la

      - name: Validate CF secrets
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          [ -n "${CLOUDFLARE_API_TOKEN}" ] || { echo "CF_API_TOKEN missing"; exit 1; }
          [ -n "${CLOUDFLARE_ACCOUNT_ID}" ] || { echo "CF_ACCOUNT_ID missing"; exit 1; }

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Wrangler diagnostics
        run: |
          npx --yes wrangler@3 --version
          npx --yes wrangler@3 whoami
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      - name: Verify account matches CF_ACCOUNT_ID
        run: |
          set -e
          json=$(npx --yes wrangler@3 whoami --format=json || true)
          echo "$json" | jq . >/dev/null 2>&1 || { echo "wrangler whoami (json) unavailable"; exit 0; }
          acc=$(echo "$json" | jq -r '.account_id // .accountId // empty')
          if [ -n "$acc" ] && [ -n "${{ secrets.CF_ACCOUNT_ID }}" ]; then
            if [ "$acc" != "${{ secrets.CF_ACCOUNT_ID }}" ]; then
              echo "Account mismatch: whoami=$acc vs CF_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }}"; exit 1;
            else
              echo "Account verified: $acc"
            fi
          fi
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      - name: List KV namespaces (diagnostic)
        working-directory: team-schedule-api
        run: |
          echo "Listing KV namespaces for account..."
          npx --yes wrangler@3 kv namespace list || true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      - name: Dry-run build with Wrangler (no deploy)
        working-directory: team-schedule-api
        run: |
          ls -la
          cat wrangler.toml
          npx --yes wrangler@3 deploy --env staging --config wrangler.toml --account-id ${{ secrets.CF_ACCOUNT_ID }} --dry-run --outdir .wrangler_tmp

      - name: Deploy with Wrangler (staging)
        working-directory: team-schedule-api
        run: |
          npx --yes wrangler@3.90.0 deploy --env staging --config wrangler.toml --account-id ${{ secrets.CF_ACCOUNT_ID }} --verbose
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
