name: Deploy API (staging) to Cloudflare Workers

on:
  push:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  deploy-staging-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy with Wrangler (staging)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: team-schedule-api
          command: deploy --env staging --config wrangler.toml
